### ISSUE TITLE
calling nftEntitiesConnection timeout when using where "events_some"

### ISSUE THREAD

**Issue by hassnian** [kodadot/loligo#58]
there's a good chance it's coming from `event_some`, maybe it's missing some primary key on indexer

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/issues/9175#issuecomment-1916637246_
            

The following query ends up timing out

``````diff

nftEntitiesConnection(
    orderBy: blockNumber_DESC
    where: {
      burned_eq: false
+      events_some: {
+        interaction_eq: BUY
+        currentOwner_eq: $account
+        caller_not_eq: $account
+    }
  }
  ) {
    totalCount
  }
``````

``````

{
  "errors": [
    {
      "message": "canceling statement due to statement timeout",
      "locations": [
        {
          "line": 25,
          "column": 3
        }
      ],
      "path": [
        "sold"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "query": "SELECT count(*) FROM (SELECT true FROM \"nft_entity\" AS \"nft_entity\" WHERE \"nft_entity\".\"burned\" = $1 AND (SELECT true FROM \"event\" AS \"event\" WHERE \"event\".\"caller\" != $2 AND \"event\".\"current_owner\" = $3 AND \"event\".\"interaction\" = $4 AND \"event\".\"nft_id\" = \"nft_entity\".\"id\" LIMIT 1) ORDER BY \"nft_entity\".\"block_number\" DESC LIMIT 101) AS rows",
          "parameters": [
            false,
            "FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9",
            "FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9",
            "BUY"
          ],
          "driverError": {
            "length": 109,
            "name": "error",
            "severity": "ERROR",
            "code": "57014",
            "file": "postgres.c",
            "line": "3312",
            "routine": "ProcessInterrupts"
          },
          "length": 109,
          "severity": "ERROR",
          "code": "57014",
          "file": "postgres.c",
          "line": "3312",
          "routine": "ProcessInterrupts",
          "sql": "SELECT count(*) FROM (SELECT true FROM \"nft_entity\" AS \"nft_entity\" WHERE \"nft_entity\".\"burned\" = $1 AND (SELECT true FROM \"event\" AS \"event\" WHERE \"event\".\"caller\" != $2 AND \"event\".\"current_owner\" = $3 AND \"event\".\"interaction\" = $4 AND \"event\".\"nft_id\" = \"nft_entity\".\"id\" LIMIT 1) ORDER BY \"nft_entity\".\"block_number\" DESC LIMIT 101) AS rows",
          "stacktrace": [
            "QueryFailedError: canceling statement due to statement timeout",
            "    at PostgresQueryRunner.query (/squid/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
            "    at async DataSource.query (/squid/node_modules/typeorm/data-source/DataSource.js:341:20)",
            "    at async EMDatabase.query (/squid/node_modules/@subsquid/graphql-server/lib/typeorm.js:12:23)",
            "    at async TypeormOpenreaderContext.executeQuery (/squid/node_modules/@subsquid/graphql-server/lib/typeorm.js:41:22)",
            "    at async resolve (/squid/node_modules/@subsquid/openreader/lib/opencrud/schema.js:483:30)"
          ]
        }
      }
    }
  ],
  "data": null
}
``````

_Originally posted by @hassnian in https://github.com/kodadot/nft-gallery/issues/9175#issuecomment-1916592597_

 

`````

  eventsConnection(
    orderBy: blockNumber_ASC
    where: {
      nft: {burned_eq: false},
      interaction_eq: BUY
      currentOwner_eq: "FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9"
      caller_not_eq: "FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9"
  }) {
    totalCount
  }

`````

**Comment by vikiival** [comment]
Wrong repo :)
